---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

driver_config:
    customize:
#      cpus: 2
#      memory: 2048	# 1.7
      memory: 4096	# 2.2.0

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-14.04
## bakhti.elk currently not supporting centos
#  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

