# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
## using second image to have python2
    #config.vm.box = "ubuntu/xenial64"
    config.vm.box = "boxcutter/ubuntu1604"
    #config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.sudo = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myrole" => ["elk4dfir" ],
       }
    end

    config.vm.define "elk4dfir" do |elk4dfir|
        elk4dfir.vm.hostname = "elk4dfir"
        elk4dfir.vm.provider "virtualbox" do |v|
          v.memory = 4096
        end
## kibana (user/pass = kibana)
        elk4dfir.vm.network "forwarded_port", guest: 5601, host: 6080
    end

end

